format_version: 10
environments:
  testing:
    environment_variables:
      BASH_ENV: /home/go/.bashrc
      DEPLOYMENT: testing
    pipelines:
      - terraform-install-aws-eks
pipelines:
  terraform-install-aws-eks:
    group: mygroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      my-material:
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/my-terraform-code.git
          shallow_clone: false
    stages:
      - prepare:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            prepare_terraform:
              tasks:
              - exec:
                command: ls
                run_if: passed



