format_version: 10
pipelines:
  deploy-java-mysql:
    group: practice
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      java-mysql-material:
        git: https://github.com/ConcreteAn9le/java-mysql-k8s.git
        branch: main
        destination: middle-folder
#        plugin_configuration:
#          id: git-path
#        options:
#          url: git@github.com:ConcreteAn9le/java-mysql-k8s.git
#          path: deploy
#          shallow_clone: false
#        destination: middle-folder
    stages:
      - default_stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            default_job:
              elasctic_profile_id: demo-app
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ./middle-folder/deploy
                    command: cd
                    run_if: passed
                - exec:
                    arguments:
                      - delete -f .
                    command: kubectl
                    run_if: passed
                - exec:
                    arguments:
                      - apply -f .
                    command: kubectl
                    run_if: passed
#                - script: |
#                    cd ./middle-folder/deploy
#                    kubectl delete -f .
#                    kubectl apply -f .


