format_version: 10
pipelines:
  deploy-java-mysql:
    group: pipeline-agent-eks-java-mysql
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      java-mysql-material:
#        git: git@github.com:ConcreteAn9le/java-mysql-k8s.git
#        branch: main
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/java-mysql-k8s.git
          path: deploy
          shallow_clone: false
    stages:
      - default_stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            default_job:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - abc
                    command: echo
                    run_if: passed

