format_version: 10
pipelines:
  terraform-install-aws-eks:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      my-material:
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/my-terraform-code.git
          shallow_clone: false
    stages:
      - setup:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            setup_eks:
              tasks:
              - exec:
                  arguments:
                  - abc
                  command: echo
                  run_if: passed



