format_version: 10
pipelines:
  terraform-install-aws-eks:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      my-material:
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/my-terraform-code.git
          path: base-infra/eks
          shallow_clone: false
    stages:
      - prepare:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            prepare_terraform:
              tasks:
              - exec:
                  arguments:
                  - abc
                  command: echo
                  run_if: passed
              artifacts:
                - build:
                    source: "base-infra/terraform.tfplan"
      - apply:
          timeout: 0
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply_terraform:
              tasks:
                - fetch:
                    stage: prepare
                    job: prepare_terraform
                    is_file: yes
                    source: "terraform.tfplan"
                    destination: "base-infra/"
                - exec:
                    arguments:
                      - def
                    command: echo
                    run_if: passed



