format_version: 10
pipelines:
  terraform-install-aws-eks:
    group: practice
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      my-material:
        git: https://github.com/ConcreteAn9le/my-terraform-code.git
        branch: main
        destination: my-terraform-resource
#        plugin_configuration:
#          id: git-path
#        options:
#          url: git@github.com:ConcreteAn9le/my-terraform-code.git
#          path: base-infra/eks
#          shallow_clone: false
#        destination: my-terraform-resource
    stages:
      - prepare:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            prepare_terraform:
              elastic_profile_id: my-infra-gocd-agent
              tasks:
                - exec:
                    arguments:
                      - apply
                    command: terraform
                    run_if: passed
              artifacts:
                - build:
                    source: "base-infra/terraform.tfplan"
      - apply:
          timeout: 0
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply_terraform:
              elastic_profile_id: my-infra-gocd-agent
              tasks:
                - fetch:
                    stage: prepare
                    job: prepare_terraform
                    is_file: yes
                    source: "terraform.tfplan"
                    destination: "base-infra/"
                - exec:
                    arguments:
                      - ./my-terraform-resource/base-infra/eks
                    command: cd
                    run_if: passed
                - exec:
                    arguments:
                      - init
                    command: terraform
                    run_if: passed
                - exec:
                    arguments:
                      - apply
                    command: terraform
                    run_if: passed
#                - script: |
#                    cd ./my-terraform-resource/base-infra/eks
#                    terraform init
#                    terraform apply





