format_version: 10
pipelines:
  gocd-agent-config:
    group: practice
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      gocd-config-material:
#        git: git@github.com:ConcreteAn9le/my-gocd-config.git
#        branch: main
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/my-gocd-config.git
          path: agent-profiles
          shallow_clone: false
    stages:
      - config_gocd_server:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            gocd_server_api_config:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - abc
                    command: echo
                    run_if: passed

