format_version: 10
environments:
  testing:
    environment_variables:
      DEPLOYMENT: testing
    pipelines:
      - homework2-base-infra-setup
pipelines:
  homework2-base-infra-setup:
    group: mygroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      my-material:
        plugin_configuration:
          id: git-path
        options:
          url: git@github.com:ConcreteAn9le/homework2.git
          shallow_clone: false
    stages:
      - prepare:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            prepare_terraform:
              tasks:
                  - exec:
                    command: make
                    arguments:
                      - prepare_base_infra
                    run_if: passed
                    artifacts:
                      - build:
                          source: "base-infra/my-vpc/terraform.tfplan"
      - apply:
          timeout: 0
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply_terraform:
              tasks:
                - fetch:
                    stage: prepare
                    job: prepare_terraform
                    is_file: yes
                    source: "terraform.tfplan"
                    destination: "base-infra/my-vpc"
                - exec:
                    command: make
                    arguments:
                      - apply_base_infra
                    run_if: passed


